services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/docker/Dockerfile
    container_name: glpi-search-frontend
    ports:
      - "3003:80"
    restart: unless-stopped
    networks:
      - glpi-network

networks:
  glpi-network:
    name: glpi-data-service_glpi-network
    external: true
